# Настройки подключения к базе данных PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Настройки валидации
spring.jpa.properties.hibernate.validator.apply_to_ddl=true

# Настройки сервера
server.port=8080

# Настройки логирования
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG